class BalanceException(Exception):
    pass
    
class BankKonto:
    def __init__(self, initialerBetrag, kontoName):
        self.saldo = initialerBetrag
        self.name = kontoName
        print(f"\nKonto '{self.name}' erstellt.\nSaldo = {self.saldo:.2f}â‚¬")

    def getBalance(self):
        print(f"\nKonto '{self.name}' Saldo = {self.saldo:.2f}â‚¬")

    def anlage(self, betrag):
        self.saldo = self.saldo + betrag
        print("\nAnlage erledigt.")
        self.getBalance()

    def viableTransaction(self, betrag):
        if self.saldo >= betrag:
            return
        else:
            raise BalanceException(
                f"\nSorry, Konto '{self.name}' hat nur ein Saldo von {self.saldo:.2f}â‚¬"
            )
        
    def auszahlung(self, betrag):
        try:
            self.viableTransaction(betrag)
            self.saldo = self.saldo - betrag
            print("\nAusahlung erledigt.")
            self.getBalance()
        except BalanceException as error:
            print(f'\nAuszahlung unterbrochen: {error}')

    def Ã¼berweisung(self, betrag, konto):
        try:
            print('\n**********\n\nÃœberweisung beginnt..ðŸšŸ')
            self.viableTransaction(betrag)
            self.auszahlung(betrag)
            konto.anlage(betrag)
            print('\nÃœberweisung erfolgt! ðŸ˜†\n\n**********')
        except BalanceException as error:
            print(f'\nÃœberweisung unterbrochenðŸ˜£ {error}')

class Zinskonto(BankKonto):
    def anlage(self, betrag):
        self.saldo = self.saldo + (betrag * 1.05)
        print("\nAnlage fertig.")
        self.getBalance()

class SparKonto(Zinskonto):
    def __init__(self, initialerBetrag, kontoName):
        super().__init__(initialerBetrag, kontoName)
        self.gebÃ¼hr = 5
    def auszahlung(self, betrag):
        try:
            self.viableTransaction(betrag + self.gebÃ¼hr)
            self.saldo = self.saldo - (betrag + self.gebÃ¼hr)
            print("\nAuszahlung erfolgt.")
            self.getBalance()
        except BalanceException as error:
            print(f'\nAusahlung unterbrochen: {error}')
